<?php
// pinoox app file, generated by app:create

return [
    'package'       => 'com_pinoox_test',
    'name'          => 'test',
    'developer'     => 'yoosef',
    'description'   => 'okay',
    'version-name'  => '1.0',
    'version-code'  => 1,
    'icon'          => 'icon.png',
    'enable'        => true,
    'theme'         => 'default',
    // 'theme-extends' => 'base', // inherit twig/assets from another theme folder
    // Multi-theme contexts (site/panel/...): see docs/pinoox-theme-contexts.md
    // 'theme-context' => 'site',
    // 'theme-contexts' => ['site' => ['theme' => 'default'], 'panel' => ['theme' => 'admin']],
    // 'alias' => array_merge(['auth' => ...], theme_flow_aliases(['site', 'panel'])),
    'lang'          => 'en',
    'router'        => [
        'routes' => [
            'routes/web.php',
            'routes/actions.php',
        ],
    ],
    // Boot-only site plugin: 'boot-global' => true,
    // Route-only (no boot.php): 'boot' => false,
    // 'runtime' => ['mode' => null, 'debug' => null],
    // 'alias' => ['auth' => App\com_pinoox_test\Flow\AuthFlow::class],
    // 'build' => ['gitignore' => true, 'exclude' => ['tests', 'node_modules']],
    // 'pinx' => ['type' => 'app', 'minpin' => 0],
];