<?php

namespace Pinoox\Terminal\Pincore;

use Pinoox\Component\Helpers\PhpFile\TestFile;
use Pinoox\Component\Package\AppEnv\AppEnvExample;
use Pinoox\Portal\FileSystem;
use Pinoox\Component\Terminal;
use Pinoox\Portal\Pinker;
use Pinoox\Support\SystemApp;
use Pinoox\Support\SystemConfig;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'app:create',
    description: 'Scaffold a new app under apps/ with routes, theme, and boot files',
)]

class MakeAppCommand extends Terminal
{
    protected function configure(): void
    {
        $this
            ->setHelp(
                <<<'HELP'
Creates a new HMVC app folder with default MVC structure.

Example:
  php pinoox app:create com_my_shop

You will be asked for display name, developer, and description.
HELP
            )
            ->addArgument('package', InputArgument::REQUIRED, 'New package name (e.g. com_my_shop — must match folder name)');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        parent::execute($input, $output);

        $name = $input->getArgument('package');
        // Prepare metadata
        $helper = $this->getHelper('question');
        $segments = explode('_', $name);
        $defaultDisplay = end($segments);
        
        // Ask for display name
        $questionName = new \Symfony\Component\Console\Question\Question(
            'Enter app display name: ',
            $defaultDisplay
        );
        $displayName = $helper->ask($input, $output, $questionName);
        
        // Ask for developer name
        $questionDev = new \Symfony\Component\Console\Question\Question(
            'Enter developer name: ',
            ''
        );
        $developer = $helper->ask($input, $output, $questionDev);
        
        // Ask for description
        $questionDesc = new \Symfony\Component\Console\Question\Question(
            'Enter description: ',
            $displayName
        );
        $description = $helper->ask($input, $output, $questionDesc);
        
        $appDir = SystemConfig::path('apps') . '/' . $name;
        $appFile = SystemConfig::rawPath('app_file', 'app.php');
        $configFolder = trim(SystemConfig::rawPath('app_config', 'config'), '/\\');

        if (FileSystem::exists($appDir)) {
            $output->writeln("<error>App '{$name}' already exists!</error>");
            return Command::FAILURE;
        }

        // Create directories
        FileSystem::mkdir([
            "{$appDir}",
            "{$appDir}/{$configFolder}",
            "{$appDir}/Controller",
            "{$appDir}/Router",
            "{$appDir}/routes",
            "{$appDir}/Flow",
            "{$appDir}/Model",
            "{$appDir}/Component",
            "{$appDir}/Portal",
            "{$appDir}/lang/en",
            "{$appDir}/database/migrations",
            "{$appDir}/database/seed",
            "{$appDir}/patches",
            "{$appDir}/theme/default",
        ]);

        // Generate app.php
        $appConfig = <<<PHP
<?php
// pinoox app file, generated by app:create

return [
    'package'       => '{$name}',
    'name'          => '{$displayName}',
    'developer'     => '{$developer}',
    'description'   => '{$description}',
    'version-name'  => '1.0',
    'version-code'  => 1,
    'icon'          => 'icon.png',
    'enable'        => true,
    'theme'         => 'default',
    // 'theme-extends' => 'base', // inherit twig/assets from another theme folder
    // Multi-theme contexts (site/panel/...): see docs/pinoox-theme-contexts.md
    // 'theme-context' => 'site',
    // 'theme-contexts' => ['site' => ['theme' => 'default'], 'panel' => ['theme' => 'admin']],
    // 'alias' => array_merge(['auth' => ...], theme_flow_aliases(['site', 'panel'])),
    'lang'          => 'en',
    'router'        => [
        'routes' => [
            'routes/web.php',
            'routes/actions.php',
        ],
    ],
    // Boot-only site plugin: 'boot-global' => true,
    // Route-only (no boot.php): 'boot' => false,
    // 'runtime' => ['mode' => null, 'debug' => null],
    // 'alias' => ['auth' => App\\{$name}\\Flow\\AuthFlow::class],
    // 'build' => ['gitignore' => true, 'exclude' => ['tests', 'node_modules']],
    // 'pinx' => ['type' => 'app', 'minpin' => 0],
];
PHP;
        FileSystem::dumpFile("{$appDir}/{$appFile}", $appConfig);
        FileSystem::dumpFile("{$appDir}/.env.example", AppEnvExample::appFile());

        // Get copyright stub content
        $stubsPath = rtrim(SystemConfig::path('stubs'), '/') . '/';
        $copyrightStub = file_get_contents($stubsPath . 'copyright.stub');

        // Generate Router/Actions.php
        $actionsClassFile = <<<PHP
<?php
{$copyrightStub}

namespace App\\{$name}\\Router;

final class Actions
{

    public const HOME = 'home';
}
PHP;
        FileSystem::dumpFile("{$appDir}/Router/Actions.php", $actionsClassFile);

        // Generate routes/actions.php
        $actionsFile = <<<PHP
<?php
{$copyrightStub}

use App\\{$name}\\Controller\\MainController;
use App\\{$name}\\Router\\Actions;
use function Pinoox\Router\action;

action(Actions::HOME, [MainController::class, 'index']);
PHP;
        FileSystem::dumpFile("{$appDir}/routes/actions.php", $actionsFile);

        // Generate routes/web.php
        $routesFile = <<<PHP
<?php
{$copyrightStub}

use App\\{$name}\\Router\\Actions;
use function Pinoox\Router\get;

get('/', '@' . Actions::HOME);
get('*', fn() => redirect(url('/')));
PHP;
        FileSystem::dumpFile("{$appDir}/routes/web.php", $routesFile);

        // Generate schedule.php
        $scheduleFile = <<<PHP
<?php
{$copyrightStub}

use Pinoox\Cron\Schedule;

return function (Schedule \$schedule): void {
    // \$schedule->command('cache:clear')->dailyAt('02:00')->name('clear-cache');
};
PHP;
        FileSystem::dumpFile("{$appDir}/schedule.php", $scheduleFile);

        $bootStub = file_get_contents($stubsPath . 'boot.stub');
        FileSystem::dumpFile("{$appDir}/boot.php", $bootStub);

        // Generate Controller/MainController.php
        $controllerFile = <<<PHP
<?php
{$copyrightStub}

namespace App\\{$name}\Controller;

use Pinoox\Component\Kernel\Controller\Controller;
use Pinoox\Portal\View;

class MainController extends Controller
{
    public function index()
    {
        return View::render('hello');
    }
}
PHP;
        FileSystem::dumpFile("{$appDir}/Controller/MainController.php", $controllerFile);

        // Generate hello.twig from stub
        $indexStub = file_get_contents($stubsPath . 'index.twig.stub');
        $indexContent = str_replace('{{appName}}', $displayName, $indexStub);
        FileSystem::dumpFile("{$appDir}/theme/default/hello.twig", $indexContent);

        // Theme partials for inline bootstrap + Vite
        FileSystem::dumpFile("{$appDir}/theme/default/partials/scripts.twig", file_get_contents($stubsPath . 'frontend/vue/partials/scripts.twig'));

        $stubVars = [
            '{{ copyright }}' => $copyrightStub,
            '{{package}}' => $name,
            '{{displayName}}' => $displayName,
            '{{description}}' => $description,
            '{{developer}}' => $developer,
        ];

        $themeManifestStub = str_replace(
            array_keys($stubVars),
            array_values($stubVars),
            file_get_contents($stubsPath . 'theme.php.stub'),
        );
        FileSystem::dumpFile("{$appDir}/theme/default/theme.php", $themeManifestStub);

        // Generate functions.php from stub
        $functionsStub = file_get_contents($stubsPath . 'functions.php.stub');
        FileSystem::dumpFile("{$appDir}/theme/default/functions.php", $functionsStub);
        FileSystem::dumpFile("{$appDir}/theme/default/.env.example", AppEnvExample::themeFile());

        foreach ([
            'app.flow.boot.stub' => 'Flow/BootFlow.php',
            'app.model.table.stub' => 'Model/Table.php',
            'app.lang.stub' => 'lang/en/app.lang.php',
            'app.composer.stub' => 'composer.json',
        ] as $stubFile => $target) {
            $content = str_replace(array_keys($stubVars), array_values($stubVars), file_get_contents($stubsPath . $stubFile));
            FileSystem::dumpFile("{$appDir}/{$target}", $content);
        }

        TestFile::scaffoldAppTests($name, $appDir);

        // Ask user to update only the Pinker baked router config
        $confirm = new \Symfony\Component\Console\Question\ConfirmationQuestion(
            "Do you want to add a route to the router config? (Y/n) ",
            true
        );
        if ($helper->ask($input, $output, $confirm)) {
            // Ask for route path
            $defaultPath = '/' . $name;
            $question = new \Symfony\Component\Console\Question\Question(
                "Enter route path for app (e.g. /{$name}): ",
                $defaultPath
            );
            $routePath = $helper->ask($input, $output, $question);

            // Ensure route path starts with a slash
            if (substr($routePath, 0, 1) !== '/') {
                $routePath = '/' . $routePath;
                $output->writeln("<comment>Added leading slash to route path: {$routePath}</comment>");
            }

            // Update Pinker-baked router config
            $sourceRouter = SystemApp::path('app-router.config.php');
            $bakedRouter = Pinker::bakedFileFromSource($sourceRouter);
            $routes = FileSystem::exists($bakedRouter)
                ? include $bakedRouter
                : (FileSystem::exists($sourceRouter) ? include $sourceRouter : []);
            $routes[$routePath] = $name;
            ksort($routes);
            $export = "<?php\n\nreturn [\n";
            foreach ($routes as $path => $pkg) {
                $export .= "    '{$path}' => '{$pkg}',\n";
            }
            $export .= "];\n";
            FileSystem::dumpFile($bakedRouter, $export);
            $output->writeln("<info>Baked route '{$routePath}' registered for app '{$name}'.</info>");
        }

        $output->writeln("<info>App '{$name}' created successfully in {$appDir}</info>");
        $output->writeln("<info>HMVC folders: Controller, Model, Flow, routes, lang, database, patches, theme</info>");
        $output->writeln("<info>Optional: add dependencies in composer.json; pinx:build runs composer install --no-dev and ships vendor/</info>");
        $output->writeln("<info>Tests scaffolded in {$appDir}/tests — run: php pinoox test {$name}</info>");
        return Command::SUCCESS;
    }
} 

