<?php

namespace Pinoox\Component\Package\Scaffold;

use Pinoox\Component\Helpers\PhpFile\TestFile;
use Pinoox\Component\Package\AppEnv\AppEnvExample;
use Pinoox\Component\Template\Frontend\ThemeFrontend;
use Pinoox\Portal\FileSystem;
use Pinoox\Portal\Pinker;
use Pinoox\Support\SystemApp;
use Pinoox\Support\SystemConfig;

class AppCreateScaffolder
{
    private string $appDir;
    private string $stubsPath;
    private string $copyrightStub;

    public function __construct(
        private readonly AppCreateInput $input,
    ) {
        $this->appDir = SystemConfig::path('apps') . '/' . $this->input->package;
        $this->stubsPath = rtrim(SystemConfig::path('stubs'), '/') . '/';
        $this->copyrightStub = (string) file_get_contents($this->stubsPath . 'copyright.stub');
    }

    public function appDir(): string
    {
        return $this->appDir;
    }

    public function exists(): bool
    {
        return FileSystem::exists($this->appDir);
    }

    public function scaffold(): AppCreateResult
    {
        $this->createDirectories();
        $this->writeAppManifest();
        $this->writeRouterFiles();
        $this->writeController();
        $this->writeBootFiles();
        $this->writeThemeBase();
        $this->applyFrontendStack();
        $this->writeSharedStubs();
        TestFile::scaffoldAppTests($this->input->package, $this->appDir);

        $routePath = null;
        if ($this->input->registerRoute && $this->input->routePath !== null) {
            $routePath = $this->registerRoute($this->input->routePath);
        }

        return new AppCreateResult(
            package: $this->input->package,
            appDir: $this->appDir,
            stack: $this->input->stack,
            profile: $this->input->profile,
            routePath: $routePath,
            nextSteps: $this->buildNextSteps($routePath),
        );
    }

    private function createDirectories(): void
    {
        $configFolder = trim(SystemConfig::rawPath('app_config', 'config'), '/\\');

        FileSystem::mkdir([
            $this->appDir,
            "{$this->appDir}/{$configFolder}",
            "{$this->appDir}/Controller",
            "{$this->appDir}/Router",
            "{$this->appDir}/routes",
            "{$this->appDir}/Flow",
            "{$this->appDir}/Model",
            "{$this->appDir}/Component",
            "{$this->appDir}/Portal",
            "{$this->appDir}/lang/en",
            "{$this->appDir}/database/migrations",
            "{$this->appDir}/database/seed",
            "{$this->appDir}/patches",
            "{$this->appDir}/theme/default",
        ]);
    }

    private function writeAppManifest(): void
    {
        $appFile = SystemConfig::rawPath('app_file', 'app.php');
        $name = $this->input->package;
        $displayName = $this->escapePhpString($this->input->displayName);
        $developer = $this->escapePhpString($this->input->developer);
        $description = $this->escapePhpString($this->input->description);

        $frontendBlock = '';
        if ($this->input->hasViteStack()) {
            $profile = $this->escapePhpString($this->input->profile);
            $stack = $this->escapePhpString($this->input->stack);
            $frontendBlock = <<<PHP

    'frontend' => [
        'profile' => '{$profile}',
        'stack' => '{$stack}',
    ],
PHP;
        }

        $appConfig = <<<PHP
<?php
// pinoox app file, generated by app:create

return [
    'package' => '{$name}',
    'name' => '{$displayName}',
    'developer' => '{$developer}',
    'description' => '{$description}',
    'version-name' => '1.0',
    'version-code' => 1,
    'icon' => 'icon.png',
    'enable' => true,
    'theme' => 'default',
    'lang' => 'en',{$frontendBlock}
    'router' => [
        'routes' => [
            'routes/web.php',
            'routes/actions.php',
        ],
    ],
];
PHP;

        FileSystem::dumpFile("{$this->appDir}/{$appFile}", $appConfig);
        FileSystem::dumpFile("{$this->appDir}/.env.example", AppEnvExample::appFile());
    }

    private function writeRouterFiles(): void
    {
        $name = $this->input->package;
        $copyright = $this->copyrightStub;

        FileSystem::dumpFile("{$this->appDir}/Router/Actions.php", <<<PHP
<?php
{$copyright}

namespace App\\{$name}\\Router;

final class Actions
{
    public const HOME = 'home';
}
PHP);

        FileSystem::dumpFile("{$this->appDir}/routes/actions.php", <<<PHP
<?php
{$copyright}

use App\\{$name}\\Controller\\MainController;
use App\\{$name}\\Router\\Actions;
use function Pinoox\\Router\\action;

action(Actions::HOME, [MainController::class, 'index']);
PHP);

        $webRoutes = $this->buildWebRoutes();
        FileSystem::dumpFile("{$this->appDir}/routes/web.php", $webRoutes);
        FileSystem::dumpFile("{$this->appDir}/schedule.php", <<<PHP
<?php
{$copyright}

use Pinoox\\Cron\\Schedule;

return function (Schedule \$schedule): void {
};
PHP);
    }

    private function buildWebRoutes(): string
    {
        $name = $this->input->package;
        $copyright = $this->copyrightStub;

        if ($this->input->hasViteStack() && $this->input->profile === AppCreateInput::PROFILE_SPA) {
            return <<<PHP
<?php
{$copyright}

use App\\{$name}\\Controller\\MainController;
use App\\{$name}\\Router\\Actions;
use function Pinoox\\Router\\get;

get('/', '@' . Actions::HOME);
get('*', [MainController::class, 'index'])->name('fallback');
PHP;
        }

        return <<<PHP
<?php
{$copyright}

use App\\{$name}\\Router\\Actions;
use function Pinoox\\Router\\get;

get('/', '@' . Actions::HOME);
get('*', fn () => redirect(url('/')));
PHP;
    }

    private function writeController(): void
    {
        $name = $this->input->package;
        $copyright = $this->copyrightStub;
        $displayName = $this->escapePhpString($this->input->displayName);
        $description = $this->escapePhpString($this->input->description);
        $methodBody = match (true) {
            $this->input->hasViteStack() && $this->input->profile === AppCreateInput::PROFILE_HYBRID => <<<PHP

        View::shareSeo([
            'title' => '{$displayName}',
            'description' => '{$description}',
            'robots' => 'index,follow',
        ]);

        return View::render('main', [
            'bootstrap' => [
                'locale' => app()->lang(),
                'title' => '{$displayName}',
            ],
        ]);
PHP,
            $this->input->hasViteStack() => <<<PHP

        return View::render('main', [
            'bootstrap' => [
                'locale' => app()->lang(),
                'title' => '{$displayName}',
            ],
        ]);
PHP,
            $this->input->usesTwigLayouts() => <<<PHP

        return View::render('pages/home', [
            'title' => '{$displayName}',
            'message' => '{$description}',
        ]);
PHP,
            default => <<<PHP

        return View::render('hello');
PHP,
        };

        FileSystem::dumpFile("{$this->appDir}/Controller/MainController.php", <<<PHP
<?php
{$copyright}

namespace App\\{$name}\\Controller;

use Pinoox\\Component\\Kernel\\Controller\\Controller;
use Pinoox\\Portal\\View;

class MainController extends Controller
{
    public function index()
    {
{$methodBody}
    }
}
PHP);
    }

    private function writeBootFiles(): void
    {
        FileSystem::dumpFile(
            "{$this->appDir}/boot.php",
            (string) file_get_contents($this->stubsPath . 'boot.stub'),
        );
    }

    private function writeThemeBase(): void
    {
        $stubVars = [
            '{{ copyright }}' => $this->copyrightStub,
            '{{package}}' => $this->input->package,
            '{{displayName}}' => $this->input->displayName,
            '{{description}}' => $this->input->description,
            '{{developer}}' => $this->input->developer,
        ];

        $themeManifest = str_replace(
            array_keys($stubVars),
            array_values($stubVars),
            (string) file_get_contents($this->stubsPath . 'theme.php.stub'),
        );
        FileSystem::dumpFile("{$this->appDir}/theme/default/theme.php", $themeManifest);

        $functionsStub = (string) file_get_contents($this->stubsPath . 'functions.php.stub');
        FileSystem::dumpFile("{$this->appDir}/theme/default/functions.php", $functionsStub);
        FileSystem::dumpFile("{$this->appDir}/theme/default/.env.example", AppEnvExample::themeFile());
    }

    private function applyFrontendStack(): void
    {
        $themeDir = "{$this->appDir}/theme/default";

        if ($this->input->stack === AppCreateInput::STACK_NONE) {
            $indexStub = (string) file_get_contents($this->stubsPath . 'index.twig.stub');
            $indexContent = str_replace('{{appName}}', $this->input->displayName, $indexStub);
            FileSystem::dumpFile("{$themeDir}/hello.twig", $indexContent);

            return;
        }

        if ($this->input->stack === AppCreateInput::STACK_TWIG) {
            ThemeFrontend::forPackageAndTheme($this->input->package, 'default')->scaffold(AppCreateInput::STACK_TWIG);
            $this->writeTwigHomePage();

            return;
        }

        ThemeFrontend::forPackageAndTheme($this->input->package, 'default')->scaffold($this->input->stack);
        $this->patchFrontendConfig("{$themeDir}/frontend.config.php");
    }

    private function writeTwigHomePage(): void
    {
        $pagesDir = "{$this->appDir}/theme/default/pages";
        if (!is_dir($pagesDir)) {
            mkdir($pagesDir, 0777, true);
        }

        FileSystem::dumpFile("{$pagesDir}/home.twig", <<<'TWIG'
{% extends 'layouts/app.twig' %}

{% block body %}
<main class="layout">
    <h1>{{ title }}</h1>
    <p>{{ message }}</p>
</main>
{% endblock %}
TWIG);
    }

    private function patchFrontendConfig(string $configFile): void
    {
        if (!is_file($configFile)) {
            return;
        }

        $content = (string) file_get_contents($configFile);
        $profile = $this->escapePhpString($this->input->profile);
        $stack = $this->escapePhpString($this->input->stack);

        $content = (string) preg_replace(
            "/'profile'\\s*=>\\s*'[^']*'/",
            "'profile' => '{$profile}'",
            $content,
            1,
        );
        $content = (string) preg_replace(
            "/'stack'\\s*=>\\s*'[^']*'/",
            "'stack' => '{$stack}'",
            $content,
            1,
        );

        FileSystem::dumpFile($configFile, $content);
    }

    private function writeSharedStubs(): void
    {
        $stubVars = [
            '{{ copyright }}' => $this->copyrightStub,
            '{{package}}' => $this->input->package,
            '{{displayName}}' => $this->input->displayName,
            '{{description}}' => $this->input->description,
            '{{developer}}' => $this->input->developer,
        ];

        foreach ([
            'app.flow.boot.stub' => 'Flow/BootFlow.php',
            'app.model.table.stub' => 'Model/Table.php',
            'app.lang.stub' => 'lang/en/app.lang.php',
            'app.composer.stub' => 'composer.json',
        ] as $stubFile => $target) {
            $content = str_replace(
                array_keys($stubVars),
                array_values($stubVars),
                (string) file_get_contents($this->stubsPath . $stubFile),
            );
            FileSystem::dumpFile("{$this->appDir}/{$target}", $content);
        }
    }

    private function registerRoute(string $routePath): string
    {
        $routePath = '/' . ltrim($routePath, '/');
        $name = $this->input->package;

        $sourceRouter = SystemApp::path('app-router.config.php');
        $bakedRouter = Pinker::bakedFileFromSource($sourceRouter);
        $routes = FileSystem::exists($bakedRouter)
            ? include $bakedRouter
            : (FileSystem::exists($sourceRouter) ? include $sourceRouter : []);
        $routes[$routePath] = $name;
        ksort($routes);

        $export = "<?php\n\nreturn [\n";
        foreach ($routes as $path => $pkg) {
            $export .= "    '{$path}' => '{$pkg}',\n";
        }
        $export .= "];\n";
        FileSystem::dumpFile($bakedRouter, $export);

        return $routePath;
    }

    /**
     * @return list<string>
     */
    private function buildNextSteps(?string $routePath): array
    {
        $package = $this->input->package;
        $steps = [
            "php pinoox test {$package}",
            "Read apps/{$package}/tests/README.md for helpers (inMyApp, myAppGet, …)",
        ];

        if ($this->input->hasViteStack()) {
            $steps[] = "php pinoox fe {$package} install";
            $steps[] = "php pinoox fe {$package} dev";
        } elseif ($routePath !== null) {
            $steps[] = "php pinoox serve --app={$package}";
        }

        if ($routePath !== null) {
            $steps[] = "Open {$routePath} in your browser (after starting the server)";
        }

        return $steps;
    }

    private function escapePhpString(string $value): string
    {
        return str_replace(['\\', "'"], ['\\\\', "\\'"], $value);
    }

    public static function normalizePackageName(string $value): string
    {
        $value = strtolower(trim($value));
        $value = preg_replace('/[^a-z0-9_]+/', '_', $value) ?? $value;
        $value = trim($value, '_');

        if ($value === '') {
            return '';
        }

        if (!str_starts_with($value, 'com_')) {
            $value = 'com_' . $value;
        }

        return $value;
    }

    public static function isValidPackageName(string $value): bool
    {
        return (bool) preg_match('/^[a-z][a-z0-9_]*$/', $value);
    }

    public static function displayNameFromPackage(string $package): string
    {
        $segments = explode('_', $package);

        return ucfirst((string) end($segments));
    }
}
