<?php
/**
 *      ****  *  *     *  ****  ****  *    *
 *      *  *  *  * *   *  *  *  *  *   *  *
 *      ****  *  *  *  *  *  *  *  *    *
 *      *     *  *   * *  *  *  *  *   *  *
 *      *     *  *    **  ****  ****  *    *
 * @author   Pinoox
 * @link https://www.pinoox.com/
 * @license  https://opensource.org/licenses/MIT MIT License
 */


namespace Pinoox\Component\event;

use Symfony\Component\EventDispatcher\EventDispatcher as EventDispatcherSymfony;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class EventDispatcher extends EventDispatcherSymfony
{
    public function listen(string $eventName, callable|array $listener, int $priority = 0): void
    {
        parent::addListener($eventName, $listener, $priority);
    }

    public function addSubscriber(EventSubscriberInterface $subscriber): void
    {
        parent::addSubscriber($subscriber); // TODO: Change the autogenerated stub
    }
}