<?php
/**
 * @license  https://opensource.org/licenses/MIT MIT License
 */

use App\com_pinoox_manager\Controller\AuthController;
use App\com_pinoox_manager\Controller\UserController;
use App\com_pinoox_manager\Controller\OptionController;
use App\com_pinoox_manager\Controller\WidgetController;
use App\com_pinoox_manager\Controller\AppController;
use App\com_pinoox_manager\Controller\RouterController;
use App\com_pinoox_manager\Controller\AccountController;
use App\com_pinoox_manager\Controller\MarketController;
use App\com_pinoox_manager\Controller\NotificationController;
use App\com_pinoox_manager\Controller\UpdateController;
use App\com_pinoox_manager\Controller\TemplateController;

return [
    [
        'method' => 'GET',
        'uri' => '/auth/lock',
        'action' => [AuthController::class, 'lock'],
        'name' => 'auth.lock',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/auth/unlock',
        'action' => [AuthController::class, 'unlock'],
        'name' => 'auth.unlock',
        'flow' => ['manager.auth'],
        'tag' => 'Authentication',
        'summary' => 'Unlock screen',
        'description' => 'Unlock the manager session after screen lock using the account password.',
    ],
    [
        'method' => 'GET',
        'uri' => '/user/get',
        'action' => [UserController::class, 'get'],
        'name' => 'user.get',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/user/getOptions',
        'action' => [UserController::class, 'getOptions'],
        'name' => 'user.getOptions',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/user/deleteAvatar',
        'action' => [UserController::class, 'deleteAvatar'],
        'name' => 'user.deleteAvatar',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/user/changeAvatar',
        'action' => [UserController::class, 'changeAvatar'],
        'name' => 'user.changeAvatar',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/user/changeInfo',
        'action' => [UserController::class, 'changeInfo'],
        'name' => 'user.changeInfo',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/user/changePassword',
        'action' => [UserController::class, 'changePassword'],
        'name' => 'user.changePassword',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/user/getUsers/{packageName}',
        'action' => [UserController::class, 'getUsers'],
        'name' => 'user.getUsers.packageName',
        'flow' => ['manager.auth'],
        'permission' => 'manager.users.view',
    ],
    [
        'method' => 'GET',
        'uri' => '/options/get',
        'action' => [OptionController::class, 'getOptions'],
        'name' => 'options.get',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/options/changeBackground/{name}',
        'action' => [OptionController::class, 'changeBackground'],
        'name' => 'options.changeBackground.name',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/options/uploadWallpaper',
        'action' => [OptionController::class, 'uploadWallpaper'],
        'name' => 'options.uploadWallpaper',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/options/deleteWallpaper/{name}',
        'action' => [OptionController::class, 'deleteWallpaper'],
        'name' => 'options.deleteWallpaper.name',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/options/changeLockTime/{minutes}',
        'action' => [OptionController::class, 'changeLockTime'],
        'name' => 'options.changeLockTime.minutes',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/options/toggleDockPin/{packageName}',
        'action' => [OptionController::class, 'toggleDockPin'],
        'name' => 'options.toggleDockPin.packageName',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/changeLang/{lang}',
        'action' => [OptionController::class, 'changeLang'],
        'name' => 'changeLang.lang',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/widget/clock',
        'action' => [WidgetController::class, 'clock'],
        'name' => 'widget.clock',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/widget/storage',
        'action' => [WidgetController::class, 'storage'],
        'name' => 'widget.storage',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/widget/storageBrowse',
        'action' => [WidgetController::class, 'browseStorage'],
        'name' => 'widget.storageBrowse',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/widget/settings',
        'action' => [WidgetController::class, 'settings'],
        'name' => 'widget.settings',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/widget/saveWidgets',
        'action' => [WidgetController::class, 'saveWidgets'],
        'name' => 'widget.saveWidgets',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/widget/storageSettings',
        'action' => [WidgetController::class, 'saveStorageSettings'],
        'name' => 'widget.storageSettings',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/app/getAll',
        'action' => [AppController::class, 'getAll'],
        'name' => 'app.getAll',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/app/get/{filter?}',
        'action' => [AppController::class, 'get'],
        'name' => 'app.get.filter',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/app/getConfig/{packageName}',
        'action' => [AppController::class, 'getConfig'],
        'name' => 'app.getConfig.packageName',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/app/setConfig/{packageName}/{key}',
        'action' => [AppController::class, 'setConfig'],
        'name' => 'app.setConfig.packageName.key',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/app/install',
        'action' => [AppController::class, 'install'],
        'name' => 'app.install',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/app/installPackage/{filename}',
        'action' => [AppController::class, 'installPackage'],
        'name' => 'app.installPackage.filename',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/app/files',
        'action' => [AppController::class, 'files'],
        'name' => 'app.files',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/app/deleteFile',
        'action' => [AppController::class, 'deleteFile'],
        'name' => 'app.deleteFile',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/app/filesUpload',
        'action' => [AppController::class, 'filesUpload'],
        'name' => 'app.filesUpload',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/app/remove/{packageName}',
        'action' => [AppController::class, 'remove'],
        'name' => 'app.remove.packageName',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/router/getAll',
        'action' => [RouterController::class, 'getAll'],
        'name' => 'router.getAll',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/router/remove',
        'action' => [RouterController::class, 'remove'],
        'name' => 'router.remove',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/router/save',
        'action' => [RouterController::class, 'save'],
        'name' => 'router.save',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/account/getConnectData',
        'action' => [AccountController::class, 'getConnectData'],
        'name' => 'account.getConnectData',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/account/connect',
        'action' => [AccountController::class, 'connect'],
        'name' => 'account.connect',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/account/logout',
        'action' => [AccountController::class, 'logout'],
        'name' => 'account.logout',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/market/getDownloads',
        'action' => [MarketController::class, 'getDownloads'],
        'name' => 'market.getDownloads',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/market/deleteDownload',
        'action' => [MarketController::class, 'deleteDownload'],
        'name' => 'market.deleteDownload',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/market/getApps/{keyword?}',
        'action' => [MarketController::class, 'getApps'],
        'name' => 'market.getApps.keyword',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/market/getOneApp/{package_name}',
        'action' => [MarketController::class, 'getOneApp'],
        'name' => 'market.getOneApp.package_name',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/market/downloadRequest/{package_name}',
        'action' => [MarketController::class, 'downloadRequest'],
        'name' => 'market.downloadRequest.package_name',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/market/getTemplates/{package_name}',
        'action' => [MarketController::class, 'getTemplates'],
        'name' => 'market.getTemplates.package_name',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/market/downloadRequestTemplate/{uid}',
        'action' => [MarketController::class, 'downloadRequestTemplate'],
        'name' => 'market.downloadRequestTemplate.uid',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/notification',
        'action' => [NotificationController::class, 'index'],
        'name' => 'notification',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/notification/hide',
        'action' => [NotificationController::class, 'hide'],
        'name' => 'notification.hide',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'POST',
        'uri' => '/notification/seen',
        'action' => [NotificationController::class, 'seen'],
        'name' => 'notification.seen',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/update/checkVersion/{type?}',
        'action' => [UpdateController::class, 'checkVersion'],
        'name' => 'update.checkVersion.type',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/update/install',
        'action' => [UpdateController::class, 'install'],
        'name' => 'update.install',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/template/get/{packageName}',
        'action' => [TemplateController::class, 'get'],
        'name' => 'template.get.packageName',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/template/install/{uid}/{packageName}',
        'action' => [TemplateController::class, 'install'],
        'name' => 'template.install.uid.packageName',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/template/installPackage/{filename}',
        'action' => [TemplateController::class, 'installPackage'],
        'name' => 'template.installPackage.filename',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/template/set/{packageName}/{folderName}',
        'action' => [TemplateController::class, 'set'],
        'name' => 'template.set.packageName.folderName',
        'flow' => ['manager.auth'],
    ],
    [
        'method' => 'GET',
        'uri' => '/template/remove/{packageName}/{folderName}',
        'action' => [TemplateController::class, 'remove'],
        'name' => 'template.remove.packageName.folderName',
        'flow' => ['manager.auth'],
    ],
];
